# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
services:
  server:
    container_name: 'sailwindcontainer'
    image: 'sailwindcontainer'
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - 'sailwind-network'

  db:
    container_name: 'postgres-container'
    user: postgres
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SailwindApiDb
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 'sailwind-network'

volumes:
  db-data:


networks:
  sailwind-network:
    driver: bridge
